### ISSUE TITLE
No actucal effects

### ISSUE THREAD

**Issue by charliie-dev** [Cologler/logseq-remove-empty-blocks-typescript#1]
After clicking the context menu item, the empty blocks still remains.

OS: Ubuntu22.04
Logseq version: 0.9.13
plugin version: v0.0.3

screenshots:
1. 
![圖片](https://github.com/Cologler/logseq-remove-empty-blocks-typescript/assets/32497323/d2ff4d79-f7eb-4222-bc76-5ae33bc01f34)

2. 
![圖片](https://github.com/Cologler/logseq-remove-empty-blocks-typescript/assets/32497323/cc228474-275c-4840-94bb-32e76fa3cf58)

3. 
![圖片](https://github.com/Cologler/logseq-remove-empty-blocks-typescript/assets/32497323/3d5890d3-bdd3-47e7-869f-f886c948608e)

**Comment by Cologler** [comment]
Are you trying to trim whitespace from a block instead of removing an empty block?

**Comment by charliie-dev** [comment]
the later

**Comment by Cologler** [comment]
Can you post the original markdown content of the test case?

**Comment by charliie-dev** [comment]
```txt
- kopkop
- jiojiojjo
-
-
```

**Comment by Cologler** [comment]
You are trying to remove blocks from the top block (the page), which is not handled currently.

I will add a page menu item in the next version.

**Comment by charliie-dev** [comment]
Indeed, this works.

```txt
- kopkop
- jiojiojjo
	- kpokopk
	-
	- kiopkopkpo
-
```

-> click `Remove empty blocks` on `- jiojiojjo`

```txt
- kopkop
- jiojiojjo
	- kpokopk
	- kiopkopkpo
-
```

**Comment by Cologler** [comment]
The new version has been released.

**Comment by charliie-dev** [comment]
Can confirm it now works on page level!
